# This file contains values from Cookiecutter

default_context:
  project_name: "lane-detection-hackathon"
  project_slug: "lane_detection_hackathon"
  project_description: "Awesome `lane-detection-hackathon` project!"
  username: "Awesome user"
  email: "awesome-user@example.com"
  vcs_remote_type: "github"
  minimal_python_version: "3.9"
  version: "0.1.0"
  line_length: "100"

  include_cli_example: "n"
  include_docker_sample: "n"
  include_tests_sample: "n"
  include_notebooks_sample: "y"
  include_mypy_linter: "n"
