project_name: Lane Markings Segmentation

enable_clearml: False

verbose: True
time_profiling: True

num_epochs: 100
seed: 42
lr: 1.0e-4

# All cores
num_workers: -1
batch_size: 1

dataset_name: apolloscape_cropped_v2
dataset_version: "2023_03_04"

# dataset_name: apolloscapes_preprocessed
# dataset_version: "2023_02_26"

label_map:
  background: 0
  SYD: 1
  BWG: 2
  SWD: 3
  SWS: 4
  CWYZ: 5

class_weights:
  background: 0.05
  SYD: 0.19
  BWG: 0.19
  SWD: 0.19
  SWS: 0.19
  CWYZ: 0.19

cell_size: 512

transformer:
  _target_: lane_detection_hackathon.transforms.LaneMarkingAlbuAugmentation

optimizer:
  _target_: torch.optim.Adam
  lr: ${lr}

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  # Must be tuned based on samples count
  patience: 10
  # cooldown: 5
  factor: 0.5
  min_lr: 1.0e-7
  verbose: True

criterion:
  _target_: torch.nn.CrossEntropyLoss
  reduction: mean

model:
  _target_: segmentation_models_pytorch.Unet
  encoder_name: resnet34
  classes: ${len:${label_map}}
